require 'multi_json'
require 'sinatra'
require 'sinatra/reloader'
require 'pg'
require 'sinatra/activerecord'
set :database_file, 'config/database.yml'

require './app/models/models'
require './lib/api_requester'
require './app/concepts/concepts'
require './app/controllers/telegram_controller'
require './app/controllers/welcome_controller'
require './app/routes'
